services:
  db:
    image: postgres:17
    hostname: db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "0.2"
          memory: 256M

  # 現在の設定では繋がらないのでコメントアウト
  # pgadmin:
  #   image: dpage/pgadmin4:8.10
  #   hostname: pgadmin
  #   ports:
  #     - 5050:80
  #   volumes:
  #     - volume_pgadmin:/var/lib/pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: example@example.com
  #     PGADMIN_DEFAULT_PASSWORD: password
  #   depends_on:
  #     db:
  #       condition: service_started

volumes:
  db_data:
    driver: local
  # volume_pgadmin:
  #   driver: local
