services:
  romu_nextjs:
    hostname: romu_nextjs
    build:
      context: romu_nextjs
      dockerfile: RomuNextJsDockerfile_development
    networks:
      - app_network
    environment:
      DATABASE_URL: postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}
      NEXT_PUBLIC_FIREBASE_API_KEY: ${NEXT_PUBLIC_FIREBASE_API_KEY}
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
      NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL: ${NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL}
      NEXT_PUBLIC_FIREBASE_PRIVATE_KEY: ${NEXT_PUBLIC_FIREBASE_PRIVATE_KEY}
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
      NEXT_PUBLIC_FIREBASE_APP_ID: ${NEXT_PUBLIC_FIREBASE_APP_ID}
      NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}
      ADMIN_VERIFY_TOKEN: ${ADMIN_VERIFY_TOKEN}
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./romu_nextjs:/romu_nextjs
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 2.5G
        reservations:
          cpus: "0.2"
          memory: 256M
    depends_on:
      db:
        condition: service_started

  db:
    image: postgres:17
    hostname: db
    networks:
      - app_network
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "0.2"
          memory: 256M

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
