openapi: "3.0.3"
info:
  title: Romu API
  version: "1.0"
servers:
  - url: https://localhost:3000/api
    description: Local server

tags:
  - name: common
    description: 共通
  - name: workout
    description: ワークアウト

paths:
  /v1/user:
    get:
      summary: ユーザ情報の取得
      tags:
        - common
      responses:
        "200":
          description: Success
          headers:
            Authorization:
              description: Authorization token
              schema:
                type: string
                description: Bearer token
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "OC4gK6P11123NasALqSshfkiopoPz3"
                  email:
                    type: string
                    example: "romu-user123@romu.com"
                  name:
                    type: string
                    example: "RoMu"
              examples:
                Success:
                  value:
                    id: "OC4gK6P11123NasALqSshfkiopoPz3"
                    email: "romu-user123@romu.com"
                    name: "RoMu"

    post:
      summary: ユーザの新規作成
      tags:
        - common
      description: サインイン/アップ時に使用
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: Success
          headers:
            Authorization:
              description: Authorization token
              schema:
                type: string
                description: Bearer token
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    example: "OC4gK6P11123NasALqSshfkiopoPz3"
                  email:
                    type: string
                    example: "romu-user123@romu.com"
                  name:
                    type: string
                    example: "RoMu"

    patch:
      summary: ユーザ情報の部分更新
      tags:
        - common
      description: ユーザ情報の編集時に使用する
      responses:
        "200":
          description: Success
          headers:
            Authorization:
              description: Authorization token
              schema:
                type: string
                description: Bearer token
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                    example: "nickname"
                    description: ユーザ名（全体に公開される）
                    nullable: true
                    minLength: 1

  /v1/workouts:
    get:
      summary: ワークアウト一覧の取得
      tags:
        - workout
      responses:
        "200":
          description: Success
          headers:
            Authorization:
              description: Authorization token
              schema:
                type: string
                description: Bearer token
          content:
            application/json:
              schema:
                type: object
                properties:
                  workouts:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                          description: ワークアウト名
                          example:
                            - ベンチプレス
                            - スクワット
                            - デッドリフト
                        memo:
                          type: string
                          description: メモ
                        type:
                          $ref: "#/components/schemas/RomuWorkoutTypeEnum"
                        part:
                          $ref: "#/components/schemas/RomuWorkoutPartEnum"
                        isDefault:
                          type: boolean
                          description: ユーザが編集可能かどうか

    patch:
      summary: ワークアウトの部分更新
      tags:
        - workout
      responses:
        "200":
          description: Success
          headers:
            Authorization:
              description: Authorization token
              schema:
                type: string
                description: Bearer token
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    nullable: false
                    example: "OC4gK6P11123NasALqSshfkiopoPz3"
                  name:
                    type: string
                    nullable: true
                    example: "ベンチプレス（バーベル）"
                  memo:
                    type: string
                    nullable: true
                    example: "2024/11/01 90kg達成\n2024/12/01 100kg達成"
                  type:
                    $ref: "#/components/schemas/RomuWorkoutTypeEnum"
                  part:
                    $ref: "#/components/schemas/RomuWorkoutPartEnum"

  /v1/workout?workoutId={workoutId}:
    get:
      summary: ワークアウトを個別で取得
      tags:
        - workout
      parameters:
        - name: workoutId
          in: path
          required: true
          description: ワークアウトID
          schema:
            type: string
            example: "OC4gK6P11123NasALqSshfkiopoPz3"
      responses:
        "200":
          description: Success
          headers:
            Authorization:
              description: Authorization token
              schema:
                type: string
                description: Bearer token
          content:
            application/json:
              schema:
                type: object
                properties:
                  editable:
                    type: boolean
                    description: 編集が可能かどうか
                    example: true
                  workout:
                    type: object
                    nullable: true
                    properties:
                      id:
                        type: string
                        example: "OC4gK6P11123NasALqSshfkiopoPz3"
                      name:
                        type: string
                        example: "ベンチプレス"
                      memo:
                        type: string
                        example: "90kg達成"
                      type:
                        $ref: "#/components/schemas/RomuWorkoutTypeEnum"
                      part:
                        $ref: "#/components/schemas/RomuWorkoutPartEnum"
                      isDefault:
                        type: boolean
                        example: false
              examples:
                SuccessEditable:
                  value:
                    editable: true
                    workout:
                      id: "OC4gK6P11123NasALqSshfkiopoPz3"
                      name: "ベンチプレス"
                      memo: "90kg達成"
                      type: 1
                      part: 1
                      isDefault: false
                SuccessNotEditable:
                  value:
                    editable: false
                    workout: null

  /v1/training?day={day}:
    get:
      summary: トレーニング記録の取得
      tags:
        - workout
      parameters:
        - name: day
          in: path
          required: true
          description: トレーニング日
          schema:
            type: string
            example: "20241101"
      responses:
        "200":
          description: Success
          headers:
            Authorization:
              description: Authorization token
              schema:
                type: string
                description: Bearer token
          content:
            application/json:
              schema:
                type: object
                properties:
                  trainingId:
                    type: string
                    example: "OC4gK6P11123NasALqSshfkiopoPz3"
                  trainedAt:
                    type: string
                    example: "20241101"
                  menu:
                    type: array
                    items:
                      type: object
                      properties:
                        workoutId:
                          type: string
                          example: "benchPress"
                        workoutName:
                          type: string
                          example: "ベンチプレス"
                        type:
                          $ref: "#/components/schemas/RomuWorkoutTypeEnum"
                        part:
                          $ref: "#/components/schemas/RomuWorkoutPartEnum"
                        trainingMemo:
                          type: string
                          description: メモ
                        set:
                          type: array
                          items:
                            type: object
                            properties:
                              weight:
                                type: number
                                description: 重量
                                example: 90
                              rep:
                                type: integer
                                description: 回数
                                example: 10
                              time:
                                type: string
                                nullable: true
                                description: 時間 hhmmss
                                example: "003000"
                              distance:
                                type: number
                                nullable: true
                                description: 距離 / km
                                example: 1000
              examples:
                Success:
                  value:
                    trainingId: "OC4gK6P11123NasALqSshfkiopoPz3"
                    trainedAt: "20241101"
                    menu:
                      - workoutId: "benchPress"
                        workoutName: "ベンチプレス"
                        type: 1
                        part: 1
                        trainingMemo: "90kg達成"
                        set:
                          - weight: 90
                            rep: 1
                          - weight: 70
                            rep: 9
                          - weight: 70
                            rep: 8
                      - workoutId: "wfnauihAsdj"
                        workoutName: "トレッドミル"
                        type: 9
                        part: 0
                        trainingMemo: ""
                        set:
                          - time: null
                            distance: 1.5
                          - time: "001500"
                            distance: null

  /health:
    get:
      summary: Health check
      tags:
        - common
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "OK"
              examples:
                Success:
                  value:
                    status: "OK"

components:
  schemas:
    RomuWorkoutTypeEnum:
      type: integer
      description: "種目の種類\n1: バーベル、2: ダンベル、3: マシン、4: ケーブル、10: 自重、9: 有酸素"
      enum:
        - 1
        - 2
        - 3
        - 4
        - 10
        - 9
    RomuWorkoutPartEnum:
      type: integer
      description: "筋肉の部位\n0: 指定なし、1: 胸、2: 背中、3: 肩、4: 腕、5: 脚、6: 腹"
      enum:
        - 0
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
