name: Run Tests

env:
  NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
  NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL: ${{ secrets.NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL }}
  NEXT_PUBLIC_FIREBASE_PRIVATE_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_PRIVATE_KEY }}

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    environment:
      name: romu-dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ./romu_nextjs/package.json
          cache: "npm"
          cache-dependency-path: "./romu_nextjs/package-lock.json"

      - name: Install dependencies
        working-directory: romu_nextjs
        run: npm ci

      - name: Run tests
        working-directory: romu_nextjs
        run: npm test --maxWorkers=100% --watchAll=false -- --coverage
